blueprint:
  name: Solakon Master–Follower (1–3 inverters, NT/HT, safety first)
  description: >
    Master–Follower control for 1–3 Solakon inverters with NT/HT tariff logic,
    balanced SoC, phase-aware power, and full safety handling (SAFE MODE).
  domain: automation
  source_url: https://github.com/dbatosc/solakon-master-follower-blueprint

  input:

    inverter_count:
      name: Number of Solakon inverters
      description: How many Solakon inverters do you have (1–3)?
      default: 2
      selector:
        number:
          min: 1
          max: 3
          step: 1
          mode: slider

    shelly_total_power:
      name: Shelly – Total grid power
      description: Total active power of the grid connection (positive = import, negative = export).
      selector:
        entity:
          domain: sensor

    master_phase_source:
      name: Master – Shelly phase power sensor
      description: Shelly phase sensor for the master inverter's phase.
      selector:
        entity:
          domain: sensor

    follower1_phase_source:
      name: Follower 1 – Shelly phase power sensor (optional)
      description: Shelly phase sensor for follower 1's phase (leave empty if not used).
      default: ""
      selector:
        entity:
          domain: sensor
          multiple: false
          include_entities: []

    follower2_phase_source:
      name: Follower 2 – Shelly phase power sensor (optional)
      description: Shelly phase sensor for follower 2's phase (leave empty if not used).
      default: ""
      selector:
        entity:
          domain: sensor
          multiple: false
          include_entities: []

    master_soc:
      name
